version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DB_PASSWORD: $DB_PASSWORD
      PORT: $PORT
    volumes:
      - .:/usr/src/app
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - db_data:/usr/local/pgsql/data
volumes:
  db_data: {}
